version: '3.8'

services:
  app:
    container_name: app
    build: 
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    env_file:
      - ./dotenv_file/.env
    depends_on:
      - psql

  psql:
    container_name: psql
    image: postgres:16.1-alpine3.19
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_file/.env
      