# Generated by Django 5.0.1 on 2024-03-05 20:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Identificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado ás')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado ás')),
                ('favicon', models.ImageField(upload_to='favicon/%Y/%m/%d', verbose_name='Favicon')),
                ('logo', models.ImageField(upload_to='logo/%Y/%m/%d', verbose_name='Logo')),
                ('footer_text', models.CharField(max_length=200, verbose_name='Texto do footer')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
    ]
