# Generated by Django 5.0.1 on 2024-02-09 01:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Identificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado ás')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado ás')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Identificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado ás')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado ás')),
                ('title', models.CharField(max_length=250, verbose_name='Título')),
                ('slug', models.SlugField(unique=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='posts/%Y/%m/%d', verbose_name='Capa')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('is_publishe', models.BooleanField(default=False, verbose_name='Publicado')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.category', verbose_name='Categoria')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
