# Generated by Django 5.0.1 on 2024-02-08 13:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Identificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado ás')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado ás')),
                ('name', models.CharField(verbose_name='Nome')),
                ('url', models.URLField(unique=True)),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
        migrations.CreateModel(
            name='LinkGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Identificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado ás')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado ás')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Título')),
                ('links', models.ManyToManyField(to='core.link')),
            ],
            options={
                'verbose_name': 'Grupo de link',
                'verbose_name_plural': 'Grupos de links',
            },
        ),
        migrations.CreateModel(
            name='SiteSetup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Identificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado ás')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado ás')),
                ('favicon', models.ImageField(upload_to='favicon/%Y/%m/%d', verbose_name='Favicon')),
                ('logo', models.ImageField(upload_to='logo/%Y/%m/%d', verbose_name='Logo')),
                ('links_groups', models.ManyToManyField(to='core.linkgroup')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
    ]
